version: '3.8'
services:
  nginx:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: nginx-server
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./dist:/usr/shared/nginx/html/
    networks:
      - bank-system-network
volumes:
  html: {}