version: "3.8"

services:
  postgres-banksystem:
    image: postgres:14.5-alpine
    restart: always
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=projectspringboot
    networks:
      - bank-system-network
networks:
  bank-system-network:
    driver: bridge